# Merge files with validated URLs


### Inputs: 
- `linkedin_company_urls_final.csv`

### Outputs:
...
  

### Purpose:

After the first run of getting and validating the URLs of all companies in the dataset, we changed our inclusion criteria and ended up with a larger number of companies. This added more URLs to the dataset, which require validation. Some of the URLs were validated manually. We therefore need to merge the manually validated URLs with the new currently unvalidated URLs.

In [36]:
import pandas as pd

In [37]:
human_validated = pd.read_csv("../data/derived/linkedin_company_urls_final.csv")
human_validated["Validated URL"] = human_validated["LinkedIn URL"]

In [38]:
ai_validated = pd.read_csv("../data/derived/linkedin_company_urls_ai_validated.csv")

In [39]:
ai_validated["LinkedIn URL"].isna().sum()

np.int64(0)

In [40]:
all_urls = ai_validated.merge(human_validated, how="left")

In [41]:
all_urls

,Company Name,LinkedIn URL,Reasoning,Is Valid,Validated URL
0,Verizon Labs,https://www.linkedin.com/company/verizon-labs,Final Assessment Reasoning:\nThe LinkedIn URL ...,True,https://www.linkedin.com/company/verizon-labs
1,ReNew Power,https://in.linkedin.com/company/renew,The LinkedIn URL provided is https://in.linked...,True,https://in.linkedin.com/company/renew
2,Citibank,https://www.linkedin.com/company/citi,"The LinkedIn URL provided is ""https://www.link...",True,https://www.linkedin.com/company/citi
3,Epic Systems Corp,https://www.linkedin.com/company/epic1979,**Reasoning:**\n\nThe LinkedIn URL provided is...,True,https://www.linkedin.com/company/epic1979
4,DC Energy,https://www.linkedin.com/company/dc-energy-llc,Final Determination:\n\nThe LinkedIn URL provi...,True,https://www.linkedin.com/company/dc-energy-llc
...,...,...,...,...,...
3234,University of Pennsylvania Perelman School of ...,https://www.linkedin.com/company/university-of...,Reasoning: The initial assessment deemed the U...,True,NaN
3235,Standard Chartered Bank,https://www.linkedin.com/company/standardchart...,Reasoning: The initial assessment was already ...,True,NaN
3236,Impact Hub Boston,https://www.linkedin.com/company/impact-hub-bo...,Reasoning: The initial assessment deemed the U...,True,NaN
3237,RapidSOS,https://www.linkedin.com/company/rapidsos,Reasoning: The initial assessment already deem...,True,NaN
3238,StepStone Group,https://www.linkedin.com/company/stepstone-group/,"Based on the provided information, the LinkedI...",True,https://www.linkedin.com/company/stepstone-group/

In [42]:
all_urls.loc[
    (all_urls["Is Valid"] == True) & (all_urls["Validated URL"].isna()), "Validated URL"
] = all_urls.loc[
    (all_urls["Is Valid"] == True) & (all_urls["Validated URL"].isna()), "LinkedIn URL"
]

In [46]:
all_urls

,Company Name,LinkedIn URL,Reasoning,Is Valid,Validated URL
0,Verizon Labs,https://www.linkedin.com/company/verizon-labs,Final Assessment Reasoning:\nThe LinkedIn URL ...,True,https://www.linkedin.com/company/verizon-labs
1,ReNew Power,https://in.linkedin.com/company/renew,The LinkedIn URL provided is https://in.linked...,True,https://in.linkedin.com/company/renew
2,Citibank,https://www.linkedin.com/company/citi,"The LinkedIn URL provided is ""https://www.link...",True,https://www.linkedin.com/company/citi
3,Epic Systems Corp,https://www.linkedin.com/company/epic1979,**Reasoning:**\n\nThe LinkedIn URL provided is...,True,https://www.linkedin.com/company/epic1979
4,DC Energy,https://www.linkedin.com/company/dc-energy-llc,Final Determination:\n\nThe LinkedIn URL provi...,True,https://www.linkedin.com/company/dc-energy-llc
...,...,...,...,...,...
3234,University of Pennsylvania Perelman School of ...,https://www.linkedin.com/company/university-of...,Reasoning: The initial assessment deemed the U...,True,https://www.linkedin.com/company/university-of...
3235,Standard Chartered Bank,https://www.linkedin.com/company/standardchart...,Reasoning: The initial assessment was already ...,True,https://www.linkedin.com/company/standardchart...
3236,Impact Hub Boston,https://www.linkedin.com/company/impact-hub-bo...,Reasoning: The initial assessment deemed the U...,True,https://www.linkedin.com/company/impact-hub-bo...
3237,RapidSOS,https://www.linkedin.com/company/rapidsos,Reasoning: The initial assessment already deem...,True,https://www.linkedin.com/company/rapidsos
3238,StepStone Group,https://www.linkedin.com/company/stepstone-group/,"Based on the provided information, the LinkedI...",True,https://www.linkedin.com/company/stepstone-group/

In [48]:
all_urls[all_urls["Validated URL"].isna()].to_excel(
    "../data/derived/flagged_linkedin_company_urls.xlsx", index=False
)

all_urls.dropna(subset=["Validated URL"]).to_csv(
    "../data/derived/linkedin_company_urls_precheck.csv", index=False
)